services:
  noe-bot:
    image: node:18-alpine
    container_name: noe-discord-bot
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && node bot.js"
    environment:
      - DISCORD_TOKEN=(YOUR_TOKEN_HERE)
    volumes:
      - /YOUR_PATH_HERE
